package com.company;

public class Main {

    public static void main(String[] args) {
	//
        int age = 20;
        String name = "Kire Beasley";
        float gpa = 3.8f;
        boolean ifGradSchool = true;

        System.out.println("Hello, my name is " + name + ".");
        System.out.println("I am " + age + " years old.");
        System.out.println("My goal is to graduate with a GPA of " + gpa + " or higher.");
        System.out.println("Do I want to attend grad school you ask? Yes, that is " + ifGradSchool + ".");


    }
}
